export const dynamicRoutes = [
    {slug: 'item', title: 'Item', mapping: 'item-page'},
    {slug: 'sub-item', title: 'Sub Item', mapping: 'item-page'},

    {menu: 'automotive', position: 0, slug: 'automotive', title: 'Automotive', mapping: 'automotive-page', image: '/assets/images/Automotive.png'},
    {menu: 'automotive', position: 1, slug: 'cars', title: 'Cars (Classified)', mapping: 'automotive-page'},
    {menu: 'automotive', position: 1, slug: 'light-commercials', title: 'Light Commercials (Classified)', mapping: 'automotive-page'},
    {menu: 'automotive', position: 1, slug: 'motorcycles', title: 'Motorcycles (Classified)', mapping: 'automotive-page'},
    {menu: 'automotive', position: 1, slug: 'motorhomes', title: 'Motorhomes (Classified)', mapping: 'automotive-page'},
    {menu: 'automotive', position: 1, slug: 'caravans-and-trailers', title: 'Caravans and Trailers (Classified)', mapping: 'automotive-page'},
    {menu: 'automotive', position: 1, slug: 'boats', title: 'Boats and Jet Skis (Classified)', mapping: 'automotive-page'},
    {menu: 'automotive', position: 1, slug: 'automotive-parts', title: 'Parts and Accessories', mapping: 'automotive-page'},
    {menu: 'automotive', position: 2, slug: 'ford-cars', title: 'Ford', mapping: 'automotive-page'},
    {menu: 'automotive', position: 2, slug: 'volkswagen-cars', title: 'Volkswagen', mapping: 'automotive-page'},
    {menu: 'automotive', position: 2, slug: 'bmw-cars', title: 'BWM', mapping: 'automotive'},
    {menu: 'automotive', position: 2, slug: 'vauxhall-cars', title: 'Vauxhall', mapping: 'automotive-page'},
    {menu: 'automotive', position: 2, slug: 'nissan-cars', title: 'Nissan', mapping: 'automotive-page'},
    {menu: 'automotive', position: 2, slug: 'maypole-cars', title: 'Maypole', mapping: 'automotive-page'},

    {menu: 'clothes-shoes-and-accessories', position: 0, slug: 'clothes-shoes-and-accessories', title: 'Clothing &amp; Accessories', mapping: 'category-page', image: '/assets/images/Fashion.png'},
    {menu: 'clothes-shoes-and-accessories', position: 1, slug: 'clothes-shoes-and-accessories', title: 'Clothing &amp; Accessories', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 1, slug: 'womens-bags-and-handbags', title: 'Womans Bags and Handbags', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 1, slug: 'other-clothes', title: 'Other Clothes', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 1, slug: 'womens-clothing', title: 'Womens Clothing', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 1, slug: 'womans-shoes', title: 'Womans Shoes', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 1, slug: 'kids-clothes-shoes-and-accessories', title: 'Kids Cloths, Shoes and Accessories', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 1, slug: 'mens-shoes', title: 'Mens Shoes', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 1, slug: 'mens-clothing', title: 'Mens Clothing', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 1, slug: 'dancewear-and-accessories', title: 'Dancewear and Accessories', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 2, slug: 'next-clothes-and-accessories', title: 'Next', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 2, slug: 'marks-and-spencer-clothes-and-accessories', title: 'Marks and Spencer', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 2, slug: 'river-island-clothes-and-accessories', title: 'River Island', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 2, slug: 'nike-clothes-and-accessories', title: 'Nike', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 2, slug: 'ralph-lauren-clothes-and-accessories', title: 'Ralph Lauren', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 2, slug: 'dkny-clothes-and-accessories', title: 'DKNY', mapping: 'category-page'},
    {menu: 'clothes-shoes-and-accessories', position: 2, slug: 'hugo-boss-clothes-and-accessories', title: 'Hugo Boss', mapping: 'category-page'},

    {menu: 'collectables', position: 0, slug: 'collectables', title: 'Collectables', mapping: 'category-page', categories: [], brands: [], image: '/assets/images/Collectables.png'},
    {menu: 'collectables', position: 1, slug: 'keyrings', title: 'Keyrings', mapping: 'category-page'},
    {menu: 'collectables', position: 1, slug: 'memorabilia', title: 'Memorabilia', mapping: 'category-page'},
    {menu: 'collectables', position: 1, slug: 'kitchenalia', title: 'Kitchenalia', mapping: 'category-page'},
    {menu: 'collectables', position: 1, slug: 'ornaments', title: 'Ornaments', mapping: 'category-page'},
    {menu: 'collectables', position: 1, slug: 'animal-collectables', title: 'Animal Collectables', mapping: 'category-page'},
    {menu: 'collectables', position: 1, slug: 'paper-and-ephemera', title: 'Paper and Ephemera', mapping: 'category-page'},
    {menu: 'collectables', position: 1, slug: 'collectable-bottles-and-pots', title: 'Collectable Bottles and Posts', mapping: 'category-page'},
    {menu: 'collectables', position: 1, slug: 'fantasy-myth-magic', title: 'Fantasy Myth Magic', mapping: 'category-page'},
    {menu: 'collectables', position: 2, slug: 'corgi', title: 'Corgi', mapping: 'category-page'},
    {menu: 'collectables', position: 2, slug: 'disney', title: 'Disney', mapping: 'category-page'},
    {menu: 'collectables', position: 2, slug: 'vitesse', title: 'Vitesse', mapping: 'category-page'},
    {menu: 'collectables', position: 2, slug: 'scalextric', title: 'Scalextric', mapping: 'category-page'},
    {menu: 'collectables', position: 2, slug: 'me-to-you', title: 'Me to You', mapping: 'category-page'},

    {menu: 'health-and-beauty', position: 0, slug: 'health-and-beauty', title: 'Health &amp; Beauty', mapping: 'category-page', categories: [], brands: [], image: '/assets/images/Health-Beauty.png'},
    {menu: 'health-and-beauty', position: 1, slug: 'make-up', title: 'Make Up', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 1, slug: 'other-health-and-beauty', title: 'Other Health and Beauty', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 1, slug: 'bath-and-body', title: 'Bath and Body', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 1, slug: 'fragrances', title: 'Fragrances', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 1, slug: 'hair-care-and-styling', title: 'Hair Care and Styling', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 1, slug: 'facial-skin-care', title: 'Facial Skin Care', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 1, slug: 'vitamins-and-dietary-supplements', title: 'Vitamins and Dietary Suppliments', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 1, slug: 'vapes-and-accessories', title: 'Vapes and Accessories', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 2, slug: 'avon', title: 'Avon', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 2, slug: 'philips', title: 'Phillips', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 2, slug: 'loreal', title: 'Loreal', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 2, slug: 'oral-b', title: 'Oral B', mapping: 'category-page'},
    {menu: 'health-and-beauty', position: 2, slug: 'nivea', title: 'Nivea', mapping: 'category-page'},

    {menu: 'home-furniture-and-diy', position: 0, slug: 'home-furniture-and-diy', title: 'Home, Furniture &amp; DIY', mapping: 'category-page', categories: [], brands: [], image: '/assets/images/Home-Garden.png'},
    {menu: 'home-furniture-and-diy', position: 1, slug: 'household-and-laundry-supplies', title: 'Household and Laundry Supplies', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 1, slug: 'other-home-Furniture-and-diy', title: 'Other Home Furnishing and DIY', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 1, slug: 'food-and-drink', title: 'Food and Drink', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 1, slug: 'furniture', title: 'Furniture', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 1, slug: 'home-decor', title: 'Home Decor', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 1, slug: 'bedding', title: 'Bedding', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 1, slug: 'stationery-and-school-equipment', title: 'Stationary and School Equipment', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 1, slug: 'cookware-dining-and-bar', title: 'Cookware Dining and Bar', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 2, slug: 'brabantia', title: 'Brabantia', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 2, slug: 'breville', title: 'Breville', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 2, slug: 'signs-by-post', title: 'Signs By Post', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 2, slug: 'silverline', title: 'Silverline', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 2, slug: 'pot-of-sweets', title: 'Pot of Sweets', mapping: 'category-page'},
    {menu: 'home-furniture-and-diy', position: 2, slug: 'redwood-collection', title: 'Redwood Collection', mapping: 'category-page'},

    {menu: 'sound-and-vision', position: 0, slug: 'sound-and-vision', title: 'Sound and Vision', mapping: 'category-page', image: '/assets/images/TV.png'},
    {menu: 'sound-and-vision', position: 1, slug: 'other-sound-and-vision', title: 'Other Sound and Vission', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 1, slug: 'portable-audio-and-headphones', title: 'Portable Audio and Heaphones', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 1, slug: 'performance-and-dj-equipment', title: 'Performance and DJ Equipment', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 1, slug: 'tvs', title: 'TVs', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 1, slug: 'tv-and-home-audio-accessories', title: 'TV and Home Audio Accessories', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 1, slug: 'tv-reception-and-set-top-boxes', title: 'TV Reception and Set Top Boxes', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 1, slug: 'home-audio-and-hifi-separates', title: 'Home Audio and Hifi Seperates', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 1, slug: 'dvd-blu-ray-and-home-cinema', title: 'DVD Blu Ray and Home Cinema', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 2, slug: 'samsung', title: 'Samsung', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 2, slug: 'lg', title: 'LG', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 2, slug: 'toshiba', title: 'Toshiba', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 2, slug: 'sony', title: 'Sony', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 2, slug: 'panasonic', title: 'Panasonic', mapping: 'category-page'},
    {menu: 'sound-and-vision', position: 2, slug: 'jvc', title: 'JVC', mapping: 'category-page'},

    {menu: 'sporting-goods', position: 0, slug: 'sporting-goods', title: 'Sporting Goods', mapping: 'category-page', image: '/assets/images/Sports.png'},
    {menu: 'sporting-goods', position: 1, slug: 'equestrian', title: 'Equestrian', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 1, slug: 'fishing', title: 'Fishing', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 1, slug: 'fitness-running-and-yoga', title: 'Fitness, Running and Yoga', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 1, slug: 'football-shirts', title: 'Football Shirts', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 1, slug: 'snooker-and-pool', title: 'Snooker and Pool', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 1, slug: 'darts', title: 'Darts', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 1, slug: 'bowls', title: 'Bowls', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 1, slug: 'cycling', title: 'Cycling', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 2, slug: 'daiwa', title: 'DAIWA', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 2, slug: 'shimano', title: 'Shimano', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 2, slug: 'mark-todd', title: 'Mark Todd', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 2, slug: 'komodo', title: 'Komodo', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 2, slug: 'm-way', title: 'M Way', mapping: 'category-page'},
    {menu: 'sporting-goods', position: 2, slug: 'nike-sporting-goods', title: 'Nike Sporting Goods', mapping: 'category-page'},

    {menu: 'toys-and-games', position: 0, slug: 'toys-and-games', title: 'Toys and Games', mapping: 'category-page', image: '/assets/images/Toys.png'},
    {menu: 'toys-and-games', position: 1, slug: 'tv-and-movie-character-toys', title: 'TV and Movies Character Toys', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 1, slug: 'other-toys-and-games', title: 'Other Toys and Games', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 1, slug: 'pre-school-and-young-children', title: 'Pre School and Young Children', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 1, slug: 'electronic-pets', title: 'Electronic Pets', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 1, slug: 'outdoor-toys-and-activities', title: 'Outdoor Toys and Activities', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 1, slug: 'action-figures', title: 'Action Figures', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 1, slug: 'games', title: 'Games', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 1, slug: 'construction-and-building-toys', title: 'Construction and Building Toys', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 2, slug: 'disney-toys-and-games', title: 'Disney', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 2, slug: 'hasbro', title: 'Hasro', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 2, slug: 'lego', title: 'Lego', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 2, slug: 'mattel', title: 'Mattel', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 2, slug: 'playmobil', title: 'Playmobil', mapping: 'category-page'},
    {menu: 'toys-and-games', position: 2, slug: 'fisher-price', title: 'Fisher Price', mapping: 'category-page'},

    {slug: 'apple', title: 'Apple', mapping: 'category-page'},
    {slug: 'disney', title: 'Disney', mapping: 'category-page'},
    {slug: 'honda', title: 'Honda', mapping: 'category-page'},
    {slug: 'lg', title: 'LG', mapping: 'category-page'},
    {slug: 'next', title: 'Next', mapping: 'category-page'},
    {slug: 'samsung', title: 'Samsung', mapping: 'category-page'},
    {slug: 'sony', title: 'Sony', mapping: 'category-page'},

]